sites:
  - url: https://www.roadtovr.com
    name: Road to VR
    max_results: 5
github:
  repository: ${GITHUB_REPOSITORY}
  issue_labels:
    - site-monitor
    - automated
    - documentation
  default_assignees:
    - ${GITHUB_ACTOR}
search:
  api_key: ${GOOGLE_API_KEY}
  search_engine_id: ${GOOGLE_SEARCH_ENGINE_ID}
  daily_query_limit: 90
  results_per_query: 10
  date_range_days: 30
agent:
  username: ${GITHUB_ACTOR}
  workflow_directory: "docs/workflow/deliverables"
  template_directory: "templates"
  output_directory: "study"
  processing:
    default_timeout_minutes: 60
    max_concurrent_issues: 3
    retry_attempts: 2
    require_review: true
    auto_create_pr: false
  git:
    branch_prefix: "agent"
    commit_message_template: "Agent: {workflow_name} for issue #{issue_number}"
    auto_push: true
  validation:
    min_word_count: 100
    require_citations: false
    spell_check: false

# AI configuration for workflow assignment
ai:
  enabled: true  # AI is now the default workflow assignment method
  model: "gpt-4o"  # GitHub Models options: gpt-4o, llama-3.2, etc.
  confidence_thresholds:
    auto_assign: 0.8   # Confidence threshold for automatic assignment
    request_review: 0.6  # Confidence threshold for requesting human review
  max_tokens: 500
  temperature: 0.3  # Lower = more consistent, higher = more creative
  # Historical data storage (future enhancement)
  history:
    storage_type: "gist"  # or "repo_file" 
    # gist_id: ${AI_HISTORY_GIST_ID}  # Uncomment when using gist storage
    file_path: ".github/ai_assignment_history.json"

storage_path: processed_urls.json
log_level: INFO