sites:
  - url: https://www.roadtovr.com
    name: Road to VR
    max_results: 2
github:
  repository: ${GITHUB_REPOSITORY}
  issue_labels:
    - site-monitor
    - automated
    - documentation
  default_assignees:
    - ${GITHUB_ACTOR}
search:
  api_key: ${GOOGLE_API_KEY}
  search_engine_id: ${GOOGLE_SEARCH_ENGINE_ID}
  daily_query_limit: 90
  results_per_query: 10
  date_range_days: 30
storage_path: processed_urls.json
log_level: INFO