sites:
  - url: example.com
    name: Example Site
    keywords:
      - documentation
      - changelog
      - release
    max_results: 10
    search_paths:
      - /docs
      - /blog
    exclude_paths:
      - /admin
      - /private
    custom_search_terms:
      - new features
      - updated
  - url: another-site.com
    name: Another Site
    keywords:
      - news
      - updates
    max_results: 5
github:
  repository: ${GITHUB_REPOSITORY}
  issue_labels:
    - site-monitor
    - automated
    - documentation
  default_assignees:
    - ${GITHUB_ACTOR}
search:
  api_key: ${GOOGLE_API_KEY}
  search_engine_id: ${GOOGLE_SEARCH_ENGINE_ID}
  daily_query_limit: 90
  results_per_query: 10
  date_range_days: 1
storage_path: processed_urls.json
log_level: INFO