---
name: "Intelligence Analysis Workflow"
description: "AI-powered intelligence analysis for threat assessment and strategic evaluation"
version: "1.0.0"

# Labels that trigger the workflow (in addition to automatic `site-monitor`)
trigger_labels:
  - "intelligence"
  - "intelligence-analyst"
  - "threat-assessment"
  - "strategic-analysis"
  - "apt"
  - "threat-actor"
  - "geopolitical"

# Trigger conditions for this workflow
triggers:
  labels:
    required:
      - "intelligence"
      - "intelligence-analyst"
    optional:
      - "threat-assessment"
      - "strategic-analysis" 
      - "apt"
      - "threat-actor"
      - "geopolitical"

# Workflow configuration
config:
  priority: "high"
  specialist_type: "intelligence-analyst"
  ai_enhanced: true
  
# Deliverables to generate
deliverables:
  - name: "intelligence_assessment"
    template: "intelligence_assessment.md"
    filename: "intelligence-analysis-{issue_number}.md"
    conditions:
      - type: "label"
        values: ["intelligence", "threat-assessment"]
        
  - name: "executive_briefing"  
    template: "executive_briefing.md"
    filename: "executive-brief-{issue_number}.md"
    conditions:
      - type: "label"
        values: ["strategic-analysis", "geopolitical"]
        
  - name: "threat_profile"
    template: "threat_profile.md" 
    filename: "threat-profile-{issue_number}.md"
    conditions:
      - type: "label"
        values: ["apt", "threat-actor"]

# Git configuration
git:
  branch_pattern: "intelligence/issue-{issue_number}"
  commit_message: "Intelligence analysis for issue #{issue_number}: {title}"
  
# Processing settings
processing:
  timeout_minutes: 10
  require_ai_analysis: true
  confidence_threshold: 0.6