name: "OSINT Research Analysis"
description: "Comprehensive OSINT research workflow for information verification and digital reconnaissance"
version: "1.0.0"

# Workflow triggers and assignment conditions
triggers:
  # Label-based triggers
  labels:
    - "osint"
    - "osint-researcher" 
    - "reconnaissance"
    - "digital-footprint"
    - "verification"
    - "source-analysis"
    - "investigation"
    - "open-source-intelligence"
    - "research"

  # Content-based triggers
  content_keywords:
    - "osint"
    - "reconnaissance"
    - "verification"
    - "digital footprint"
    - "public records"
    - "social media"
    - "domain analysis"
    - "cross-reference"
    - "investigate"

  # Assignment conditions
  assignee: ["github-copilot[bot]", "copilot"]
  
  # Minimum confidence threshold for auto-assignment
  confidence_threshold: 0.75

# Specialist agent configuration
specialist:
  type: "osint-researcher"
  priority_weight: 0.8
  
  # OSINT-specific extraction focus areas
  extraction_focus:
    - "digital_footprint"
    - "public_records"
    - "technical_infrastructure"  
    - "social_media_presence"
    - "domain_information"
    - "contact_details"
    - "verification_sources"
    - "credibility_indicators"

# Workflow processing steps
processing_steps:
  1_content_extraction:
    method: "multi_stage"
    specialist_focused: true
    refinement_enabled: true
    confidence_threshold: 0.85
  
  2_osint_analysis:
    ai_enhanced: true
    fallback_enabled: true
    analysis_depth: "comprehensive"
    verification_focus: true
  
  3_deliverable_generation:
    template: "osint_research_report"
    format: "markdown" 
    sections:
      - "executive_summary"
      - "digital_footprint_assessment"
      - "source_verification"
      - "research_findings"
      - "verification_recommendations"
      - "intelligence_gaps"
      - "collection_plan"

# Output deliverables configuration  
deliverables:
  - name: "osint-research-report"
    title: "OSINT Research Analysis Report"
    description: "Comprehensive OSINT research analysis and verification assessment"
    template: "osint_research_report.md"
    priority: "high"
    
    # Conditional deliverable sections based on content analysis
    conditional_sections:
      digital_footprint:
        condition: "has_digital_entities"
        sections: ["domain_analysis", "social_media_assessment", "technical_infrastructure"]
      
      verification_assessment:
        condition: "has_verification_targets"
        sections: ["source_credibility", "cross_reference_opportunities", "validation_steps"]
      
      research_gaps:
        condition: "has_intelligence_gaps"
        sections: ["gap_analysis", "collection_requirements", "research_priorities"]

  - name: "verification-checklist"
    title: "Information Verification Checklist"
    description: "Actionable checklist for verifying identified information"
    template: "verification_checklist.md"
    priority: "medium"
    
    conditions:
      - has_entities_requiring_verification: true
      - verification_targets_count: "> 0"

# Git workflow configuration
git_workflow:
  branch_prefix: "osint-research"
  branch_name_pattern: "osint-research/issue-{issue_number}-{timestamp}"
  
  commit_messages:
    analysis: "feat: OSINT research analysis for issue #{issue_number}"
    deliverables: "docs: OSINT research report and verification checklist"
    
  file_organization:
    base_path: "intelligence/osint"
    structure:
      - "reports/osint-{issue_number}-report.md"
      - "checklists/verification-{issue_number}-checklist.md" 
      - "raw-data/osint-{issue_number}-data.json"

# Quality assurance and validation
quality_assurance:
  minimum_confidence_score: 0.7
  required_sections: ["digital_footprint_assessment", "verification_recommendations"]
  
  validation_rules:
    - rule: "digital_entities_identified"
      condition: "digital_entities_count > 0"
      severity: "warning"
      message: "No digital entities identified for OSINT analysis"
      
    - rule: "verification_targets_specified"  
      condition: "verification_targets_count > 0"
      severity: "info"
      message: "Consider identifying entities that require verification"
      
    - rule: "research_gaps_documented"
      condition: "intelligence_gaps_count >= 0"
      severity: "info" 
      message: "Research gaps help guide future collection efforts"

# Integration settings
integrations:
  github:
    auto_assign_specialist: true
    update_labels: true
    add_labels: ["osint-analysis-complete"]
    
  notifications:
    completion: 
      enabled: true
      message: "OSINT research analysis completed. Review digital footprint assessment and verification recommendations."
    
    verification_required:
      enabled: true
      condition: "verification_targets_count > 3"
      message: "Multiple entities require verification. Prioritize high-value targets."

# Metadata and tracking
metadata:
  workflow_version: "1.0.0"
  specialist_agent: "osint-researcher"
  analysis_methodology: "osint_research_framework"
  created_by: "ai_workflow_assignment_agent"
  last_updated: "2024-01-01T00:00:00Z"