name: Operations - Setup Monitoring

on:
  workflow_dispatch:
    # Manual trigger only

permissions:
  contents: read
  issues: write

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Set up repository for site monitoring
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Check for configuration file
        run: |
          if [ ! -f config.yaml ]; then
            echo "⚠️ Configuration file config.yaml not found"
            echo "Creating example configuration..."
            
            # Create a basic config.yaml from the template
            cp config.yaml config.yaml.example 2>/dev/null || echo "No template found"
            
            echo "📝 Please create and configure config.yaml before running monitoring"
          else
            echo "✅ Configuration file found"
          fi
      
      - name: Set up repository labels and configuration
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_SEARCH_ENGINE_ID: ${{ secrets.GOOGLE_SEARCH_ENGINE_ID }}
        run: |
          if [ -f config.yaml ]; then
            echo "🔧 Setting up repository for site monitoring..."
            python main.py setup --config config.yaml
            echo "✅ Repository setup completed"
          else
            echo "⚠️ Skipping setup - no configuration file found"
          fi
      
      - name: Show monitoring status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_SEARCH_ENGINE_ID: ${{ secrets.GOOGLE_SEARCH_ENGINE_ID }}
        run: |
          if [ -f config.yaml ]; then
            echo "📊 Current monitoring status:"
            python main.py status --config config.yaml
          else
            echo "⚠️ Cannot show status - no configuration file found"
          fi
      
      - name: Create setup completion issue
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python main.py create-issue \
            --title "✅ Site Monitoring Setup Completed - $(date -u +%Y-%m-%d)" \
            --body "The site monitoring system has been successfully set up for this repository.

          ## 🎯 Next Steps

          1. **Configure monitoring targets**: Update \`config.yaml\` with the sites you want to monitor
          2. **Set up API credentials**: Ensure \`GOOGLE_API_KEY\` and \`GOOGLE_SEARCH_ENGINE_ID\` secrets are configured
          3. **Test the system**: Run the monitoring workflow manually to test your configuration
          4. **Review schedule**: The monitoring runs daily at 9:00 AM UTC - adjust if needed

          ## 📋 Setup Summary

          - **Repository**: ${{ github.repository }}
          - **Setup Date**: $(date -u)
          - **Monitoring Labels**: Created
          - **Workflow**: Ready

          ## 🔗 Useful Links

          - [Monitoring Workflow](${{ github.server_url }}/${{ github.repository }}/actions/workflows/ops-site-monitoring.yml)
          - [Configuration Guide](./README.md)
          - [Setup Workflow Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

          ---
          *This issue was automatically created by the site monitoring setup workflow.*" \
            --labels "site-monitor" "setup" "documentation"