name: Operations -X Weekly Cleanup

on:
  # schedule:
  #   # Run weekly on Sundays at 2:00 AM UTC
  #   - cron: '0 2 * * 0'
  workflow_dispatch:
    # Allow manual triggering
    inputs:
      days_old:
        description: 'Days old threshold for cleanup'
        required: false
        type: number
        default: 7
      dry_run:
        description: 'Dry run mode (only show what would be cleaned)'
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  issues: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Clean up old monitoring data
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run cleanup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_SEARCH_ENGINE_ID: ${{ secrets.GOOGLE_SEARCH_ENGINE_ID }}
        run: |
          # Set default values
          DAYS_OLD="${{ github.event.inputs.days_old || '7' }}"
          DRY_RUN="${{ github.event.inputs.dry_run || 'false' }}"
          
          # Build command arguments
          ARGS="cleanup --config config.yaml --days-old $DAYS_OLD"
          
          if [ "$DRY_RUN" = "true" ]; then
            ARGS="$ARGS --dry-run"
          fi
          
          echo "🧹 Running cleanup with arguments: $ARGS"
          python main.py $ARGS
      
      - name: Upload cleanup logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cleanup-logs-${{ github.run_number }}
          path: |
            site_monitor.log
            processed_urls.json
          retention-days: 30